// <auto-generated />
using System;
using InvoiceManagement.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvoiceManagement.Infrastructure.Migrations
{
    [DbContext(typeof(InvoiceMySQLContext))]
    partial class InvoiceMySQLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("InvoiceManagement.Domain.Invoice", b =>
                {
                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("InvoiceNumber");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            InvoiceNumber = "1234",
                            InvoiceDate = new DateTime(2024, 6, 26, 15, 0, 13, 66, DateTimeKind.Local).AddTicks(5270),
                            OrderNumber = "1",
                            Status = "Paid",
                            SupplierName = "Logitech",
                            UserName = "John Doe"
                        },
                        new
                        {
                            InvoiceNumber = "2345",
                            InvoiceDate = new DateTime(2024, 6, 26, 15, 0, 13, 66, DateTimeKind.Local).AddTicks(5326),
                            OrderNumber = "2",
                            Status = "Paid",
                            SupplierName = "Pokemon",
                            UserName = "Brock"
                        },
                        new
                        {
                            InvoiceNumber = "3456",
                            InvoiceDate = new DateTime(2024, 6, 26, 15, 0, 13, 66, DateTimeKind.Local).AddTicks(5329),
                            OrderNumber = "3",
                            Status = "Paid",
                            SupplierName = "RedBull",
                            UserName = "Max Doe"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
